spring:
  application:
    name: "Service for News from public news API's"
server:
  port: 9735
  servlet:
    context-path: /gnews
news:
  api:
    url: https://gnews.io/api/v4
    key: your-news-api-key-here
